const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/getl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.TEST_URL||'http://localhost:4177';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage(),errors=[],passed=[];page.on('pageerror',e=>errors.push(e.message));
 const feeds=Object.fromEntries(await Promise.all(['valorant','cs2','lol','apex'].map(async game=>{const r=await fetch(base+'/api/feed?game='+game);assert.equal(r.status,200);return [game,await r.json()];})));
 async function check(name,fn){await fn();passed.push(name);console.log('PASS '+name);}
 const synced=()=>page.waitForFunction(()=>document.querySelectorAll('.source-chip.ready').length===4,{},{timeout:55000});
 const chooseGame=async game=>{await page.locator('.game-select summary').click();await page.locator('[data-action="select-game"][data-game="'+game+'"]').click();};
 const chooseBracket=async game=>{await page.locator('.game-select summary').click();await page.locator('[data-action="bracket-game"][data-game="'+game+'"]').click();};
 await page.goto(base+'/schedule');await synced();
 await check('live official feeds for all four games have provenance and valid times',async()=>{for(const f of Object.values(feeds)){assert.ok(f.matches.length>0);assert.ok(f.source.retrievedAt);assert.ok(f.source.url.startsWith('https://'));assert.ok(f.matches.every(m=>m.startsAt&&m.date&&m.id.startsWith(f.game+':')));}});
 await check('new browser defaults to dark mode with a reachable toggle',async()=>{assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.ok(await page.locator('.theme-toggle[data-action="theme"]').isVisible());assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).colorScheme),'dark');});
 await check('theme toggles both ways and persists after reload',async()=>{await page.locator('[data-action="theme"]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.reload();await synced();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('[data-action="theme"]').click();await page.reload();await synced();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');});
 await check('demo controls and manual score inputs have been completely removed',async()=>{assert.equal(await page.locator('[data-action="simulate"],[data-action="result"],[data-action="reset-bracket"],#result-form,input[name="score0"]').count(),0);assert.ok(!/本地演示|模拟下一|录入赛果|演示比赛/.test(await page.locator('body').innerText()));});
 await check('all tournament menu labels are Chinese while native Chinese titles take precedence',async()=>{await page.locator('.event-select summary').click();const labels=await page.locator('[data-action="select-event"]>span').allTextContents();assert.ok(labels.length>0);assert.ok(labels.every(t=>/[\u3400-\u9fff]/.test(t)));const champion=feeds.valorant.events.find(e=>e.name.startsWith('Champions ·'));assert.equal(champion.nameZh,'2026无畏契约全球冠军赛');assert.ok(labels.some(t=>t.includes(champion.nameZh)));assert.ok(labels.some(t=>t.includes('ESL 职业联赛第24赛季')));assert.ok(labels.some(t=>t.includes('ALGS 第6年')));assert.ok(!labels.some(t=>/Champions Shanghai|Game Changers|EMEA Masters|Pro League Season/.test(t)));await page.locator('.event-select summary').click();});
 await check('native Chinese names, source provenance and bilingual search work together',async()=>{await chooseGame('valorant');const champion=feeds.valorant.events.find(e=>e.nameZh==='2026无畏契约全球冠军赛');assert.ok(champion);const match=feeds.valorant.matches.find(m=>m.eventId===champion.id&&m.stage==='Groups');assert.ok(match);await page.locator('[data-action="pick-date"]').fill(match.date);await page.locator('.event-select summary').click();await page.locator('[data-action="select-event"][data-event="'+champion.id+'"]').click();const row=page.locator('.match-row[data-id="'+match.id+'"]');assert.ok((await row.innerText()).includes(champion.nameZh));assert.ok((await row.innerText()).includes('小组赛'));await row.click();assert.ok((await page.locator('.modal-league').innerText()).includes(champion.nameZh));await page.locator('.original-name-info summary').click();assert.ok((await page.locator('.original-name-info').innerText()).includes(champion.name));assert.ok((await page.locator('.original-name-info').innerText()).includes('无畏契约中国赛事官网'));assert.equal(await page.locator('.original-name-info a').getAttribute('href'),champion.nameSource.url);await page.locator('[data-action="close"]').click();await page.locator('#search').fill('全球冠军赛');const chinese=await page.locator('.match-row').count();assert.ok(chinese>0);await page.locator('#search').fill('Champions');assert.equal(await page.locator('.match-row').count(),chinese);await page.locator('#search').fill('');await chooseGame('all');await page.locator('[data-action="today"]').click();});
 await check('all game filters show only officially fetched matches',async()=>{for(const game of ['valorant','cs2','lol','apex']){await chooseGame(game);await page.locator('[data-action="nearest-date"]').count()&&await page.locator('[data-action="nearest-date"]').click();const ids=await page.locator('.match-row,.live-card-body').evaluateAll(xs=>xs.map(x=>x.dataset.id));assert.ok(ids.length>0,game);assert.ok(ids.every(id=>id.startsWith(game+':')));assert.ok(ids.every(id=>feeds[game].matches.some(m=>m.id===id)));}await chooseGame('all');await page.locator('[data-action="today"]').click();});
 await check('date, event and finished-state filters use real official values',async()=>{await chooseGame('lol');const finished=feeds.lol.matches.find(m=>m.status==='finished');await page.locator('[data-action="pick-date"]').fill(finished.date);await page.locator('.event-select summary').click();await page.locator('[data-action="select-event"][data-event="'+finished.eventId+'"]').click();await page.locator('[data-action="status"][data-status="finished"]').click();const ids=await page.locator('.match-row').evaluateAll(xs=>xs.map(x=>x.dataset.id));assert.ok(ids.length>0);assert.ok(ids.every(id=>feeds.lol.matches.find(m=>m.id===id).status==='finished'));await page.locator('[data-action="reset-filters"]').count()&&await page.locator('[data-action="reset-filters"]').click();await chooseGame('all');await page.locator('[data-action="today"]').click();await page.locator('[data-action="status"][data-status="all"]').click();});
 await check('match details contain separate official and third-party watching groups',async()=>{await page.locator('.match-row').first().click();assert.deepEqual(await page.locator('.watch-group h3').allTextContents(),['官方渠道','第三方平台']);const links=await page.locator('.watch-link').evaluateAll(xs=>xs.map(x=>({href:x.href,target:x.target,rel:x.rel,text:x.innerText})));assert.ok(links.length>=4);assert.ok(links.every(l=>l.href.startsWith('https://')&&l.target==='_blank'&&l.rel.includes('noopener')));for(const p of ['虎牙','斗鱼','哔哩哔哩'])assert.ok(links.some(l=>l.text.includes(p)&&l.text.includes('搜索')));assert.equal(await page.locator('dialog input').count(),0);await fs.mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/dark-watch.png'});await page.locator('[data-action="close"]').click();});
 await check('follow state survives reload without rewriting official scores',async()=>{const button=page.locator('.match-row [data-action="follow"]').first(),id=await button.getAttribute('data-id');await button.click();assert.equal(await page.locator('dialog[open]').count(),0);await page.locator('.main-nav [data-route="following"]').click();assert.ok(await page.locator('.match-row[data-id="'+id+'"]').count());await page.reload();await synced();assert.ok(await page.locator('.match-row[data-id="'+id+'"]').count());await page.locator('.match-row[data-id="'+id+'"] [data-action="follow"]').click();assert.equal(await page.locator('.match-row[data-id="'+id+'"]').count(),0);await page.locator('.main-nav [data-route="schedule"]').click();});
 await check('official source disclosure displays links, coverage and real retrieval timestamps',async()=>{await page.locator('.source-disclosure summary').click();assert.equal(await page.locator('.source-disclosure a').count(),4);assert.ok((await page.locator('.source-disclosure').innerText()).includes('北京时间'));assert.ok((await page.locator('.source-disclosure').innerText()).includes('不代表全部 CS2'));await page.locator('.source-disclosure summary').click();});
 await check('CS2 bracket uses real official edges and stays read-only',async()=>{await page.locator('.main-nav [data-route="bracket"]').click();await chooseBracket('cs2');assert.ok(await page.locator('.official-match-card').count()>0);assert.ok(await page.locator('.bracket-lines path').count()>0);assert.equal(await page.locator('[data-action="result"],[data-action="simulate"]').count(),0);await page.locator('[data-action="zoom"][data-step="-0.1"]').click();assert.ok(Number((await page.locator('[data-zoom-label]').innerText()).replace('%',''))>=50);await page.locator('[data-action="zoom"][data-step="0.1"]').click();await page.waitForFunction(()=>document.querySelectorAll('.toast').length===0);await page.screenshot({path:'docs/screenshots/dark-bracket.png',fullPage:true});});
 await check('Swiss diagram uses official groups and outcomes, with match detail and fit controls',async()=>{const snapshot=await page.evaluate(()=>JSON.parse(localStorage.getItem('matchpoint:official-cache:v1')).feeds.cs2),eventId=await page.locator('.event-select [data-action="bracket-event"]').evaluateAll(xs=>xs.find(x=>x.querySelector('.icon'))?.dataset.event),stage=snapshot.brackets.find(b=>b.eventId===eventId&&b.format==='swiss-16');assert.ok(stage);assert.equal(await page.locator('.swiss .map-group').count(),stage.groups.length);assert.ok(await page.locator('.swiss [data-edge-kind="group-flow"]').count()>0);const ids=await page.locator('.swiss .map-match').evaluateAll(xs=>xs.map(x=>x.dataset.id));assert.deepEqual(ids.sort(),stage.groups.flatMap(g=>g.matchIds).sort());assert.ok((await page.locator('.map-description').first().innerText()).includes('重新配对'));const before=Number((await page.locator('[data-zoom-label]').innerText()).replace('%',''));await page.locator('[data-action="zoom"][data-step="0.1"]').click();assert.ok(Number((await page.locator('[data-zoom-label]').innerText()).replace('%',''))>before);await page.locator('[data-action="zoom-fit"]').click();await page.locator('.swiss .map-match').first().click();assert.equal(await page.locator('.watch-group').count(),2);await page.locator('[data-action="close"]').click();await page.screenshot({path:'docs/screenshots/dark-mindmap.png',fullPage:true});await page.locator('.official-stage').first().screenshot({path:'docs/screenshots/swiss-mindmap.png'});});
 await check('Mind map is contained at mobile widths and supports dragging at desktop zoom',async()=>{for(const width of [360,390,640,768,1024,1440]){await page.setViewportSize({width,height:950});const d=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));assert.ok(d.s<=d.w,JSON.stringify(d));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/mobile-dark-mindmap.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});for(let i=0;i<7;i++)await page.locator('[data-action="zoom"][data-step="0.1"]').click();const scroll=page.locator('.mindmap-scroll').first(),box=await scroll.boundingBox();await scroll.evaluate(n=>n.scrollLeft=0);await page.mouse.move(box.x+500,box.y+57);await page.mouse.down();await page.mouse.move(box.x+220,box.y+57,{steps:8});await page.mouse.up();assert.ok(await scroll.evaluate(n=>n.scrollLeft)>150);await page.locator('[data-action="zoom-fit"]').click();});
 await check('Riot stages remain honest when official topology is unpublished',async()=>{await chooseBracket('valorant');assert.ok(await page.locator('.map-match, .duel-card').count()>0);assert.ok(await page.locator('.mindmap-canvas.stage-panels .map-matches').count()>0);assert.equal(await page.locator('.membership .map-matches').count(),0);assert.ok(await page.locator('[data-edge-kind="membership"]').count()>0);assert.equal(await page.locator('[data-edge-kind="official-advancement"]').count(),0);assert.ok((await page.locator('.official-topology-note').innerText()).includes('不推测晋级对手'));assert.equal(await page.locator('.bracket-lines path').count(),0);});
 await check('Riot stages render every official match once, as compact day panels or knockout cards',async()=>{for(const game of ['valorant','lol']){await chooseBracket(game);const event=await page.locator('.event-select [data-action="bracket-event"]').evaluateAll(xs=>xs.find(x=>x.querySelector('.icon'))?.dataset.event),panelRows=await page.locator('.map-match').evaluateAll(xs=>xs.map(n=>n.dataset.id)),ids=[...panelRows,...await page.locator('.duel-card').evaluateAll(xs=>xs.map(n=>n.dataset.id))],snapshot=await page.evaluate(game=>JSON.parse(localStorage.getItem('matchpoint:official-cache:v1')).feeds[game],game);assert.deepEqual(ids.sort(),snapshot.matches.filter(m=>m.eventId===event).map(m=>m.id).sort());assert.ok(panelRows.length>0,game+' group stage renders compact day panels');if(await page.locator('.duel-card').count()){const metrics=await page.locator('.duel-card').first().evaluate(n=>({width:n.getBoundingClientRect().width,teamFont:parseFloat(getComputedStyle(n.querySelector('.duel-opponent strong')).fontSize),vsFont:parseFloat(getComputedStyle(n.querySelector('.duel-versus b')).fontSize)}));assert.ok(metrics.width>=240&&metrics.teamFont>=16&&metrics.vsFont>=21);}await page.locator(panelRows.length?'.map-match':'.duel-card').first().click();assert.equal(await page.locator('.watch-group').count(),2);await page.locator('[data-action="close"]').click();await page.locator('.official-stage').first().screenshot({path:'docs/screenshots/'+game+'-separated-stage.png'});}});
 await check('ALGS rankings and qualification flags match the official response',async()=>{await chooseBracket('apex');await page.waitForSelector('.apex-team-row',{timeout:55000});const selected=await page.locator('.event-select .event-option').evaluateAll(xs=>xs.find(x=>x.querySelector('.icon'))?.dataset.event);const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('matchpoint:preferences:v2')));const snapshot=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('matchpoint:apex-cache:')).map(k=>JSON.parse(localStorage.getItem(k))));assert.ok(snapshot.length);const data=snapshot.at(-1),rows=data.phases.flatMap(p=>p.rows);assert.equal(await page.locator('.apex-team-row').count(),rows.length);assert.equal(await page.locator('.apex-team-row.qualifying').count(),rows.filter(t=>t.qualified).length);assert.ok((await page.locator('.official-topology-note').innerText()).includes('未标记晋级不代表淘汰'));});
 await check('phone and desktop widths have no page overflow and keep the theme toggle accessible',async()=>{await page.locator('.main-nav [data-route="schedule"]').click();await chooseGame('all');await page.locator('[data-action="today"]').click();for(const width of [360,390,640,768,1024,1440]){await page.setViewportSize({width,height:900});const dimension=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(dimension.scroll<=dimension.width,width+': '+JSON.stringify(dimension));assert.ok(await page.locator('.theme-toggle[data-action="theme"]').isVisible());}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/mobile-dark-schedule.png',fullPage:true});await page.locator('.match-row').first().click();assert.ok((await page.locator('dialog').boundingBox()).width<=390);assert.equal(await page.locator('.watch-group').count(),2);await page.screenshot({path:'docs/screenshots/mobile-dark-watch.png'});await page.locator('[data-action="close"]').click();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'docs/screenshots/dark-schedule.png',fullPage:true});});
 await check('Official archive catalogs and persisted diagrams cover all four games without making up missing results',async()=>{const response=await fetch(base+'/api/archive');assert.equal(response.status,200);const archive=await response.json();assert.ok(archive.records.length>0);for(const game of ['cs2','valorant','lol','apex']){const own=archive.records.filter(r=>r.game===game);assert.ok(own.length>0);const record=own.find(r=>r.archivedAt);assert.ok(record);const r=await fetch(base+'/api/archive/event?id='+encodeURIComponent(record.id));assert.equal(r.status,200);const saved=await r.json();assert.equal(saved.record.id,record.id);assert.ok(saved.archivedAt&&saved.diagrams?.version);assert.ok(saved.feed.matches.length>0);assert.ok(saved.feed.matches.every(m=>m.eventId===record.id));assert.ok(saved.feed.source.retrievedAt);}});
 await check('Archive game/year/search filters open historical large-card diagrams, details and export',async()=>{await page.locator('.main-nav [data-route="archive"]').click();await page.waitForSelector('.archive-event-card',{timeout:55000});await page.locator('.game-select summary').click();await page.locator('[data-action="archive-game"][data-game="valorant"]').click();await page.locator('[data-archive-filter="year"]').selectOption('2023');const cards=await page.locator('.archive-event-card').evaluateAll(xs=>xs.map(x=>({id:x.dataset.event,text:x.innerText})));assert.ok(cards.length>0&&cards.every(c=>c.id.startsWith('valorant:')&&c.text.includes('2023')));await page.locator('#search').fill('东京大师赛');await page.waitForSelector('.archive-event-card');assert.ok((await page.locator('.archive-event-card').allTextContents()).every(t=>t.includes('东京大师赛')));const id=await page.locator('.archive-event-card').first().getAttribute('data-event');await page.locator('.archive-event-card').first().click();await page.waitForSelector('.archive-diagram',{timeout:55000});const saved=await (await fetch(base+'/api/archive/event?id='+encodeURIComponent(id))).json();assert.equal(await page.locator('.map-match, .duel-card').count(),saved.feed.matches.length);await page.locator('.map-match, .duel-card').first().click();assert.ok((await page.locator('.modal-league').innerText()).includes('东京'));assert.equal(await page.locator('.watch-group').count(),2);await page.locator('[data-action="close"]').click();const download=page.waitForEvent('download');await page.locator('[data-action="archive-export"]').click();const file=await download;const exported=JSON.parse(await fs.readFile(await file.path(),'utf8'));assert.equal(exported.record.id,id);assert.deepEqual(exported.feed.matches,saved.feed.matches);assert.ok(exported.diagrams.events.length);await page.locator('.archive-diagram').screenshot({path:'docs/screenshots/archived-tokyo-2023.png'});await page.locator('[data-action="archive-back"]').click();await page.locator('#search').fill('');});
 await check('Archive listing and diagrams contain overflow on desktop and mobile widths',async()=>{for(const width of [360,390,640,768,1024,1440]){await page.setViewportSize({width,height:950});const d=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));assert.ok(d.s<=d.w,width+': '+JSON.stringify(d));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/mobile-archive-center.png',fullPage:true});await page.locator('.archive-event-card').first().click();await page.waitForSelector('.archive-diagram');assert.ok(await page.locator('.map-match, .duel-card').count()>0);assert.ok((await page.evaluate(()=>document.documentElement.scrollWidth))<=390);await page.screenshot({path:'docs/screenshots/mobile-archive-diagram.png',fullPage:true});await page.locator('[data-action="archive-back"]').click();await page.setViewportSize({width:1440,height:1000});await page.locator('.game-select summary').click();await page.locator('[data-action="archive-game"][data-game="all"]').click();await page.screenshot({path:'docs/screenshots/archive-center.png',fullPage:true});});
 await check('Saved historical diagram opens offline without pretending to have new official data',async()=>{await page.locator('.game-select summary').click();await page.locator('[data-action="archive-game"][data-game="valorant"]').click();await page.locator('[data-archive-filter="year"]').selectOption('2023');await page.locator('#search').fill('东京大师赛');await page.locator('.archive-event-card').first().click();await page.waitForSelector('.archive-diagram');await context.setOffline(true);await page.reload();await page.waitForSelector('.archive-diagram',{timeout:55000});assert.ok(await page.locator('.map-match, .duel-card').count()>0);assert.ok((await page.locator('.connection-state').innerText()).includes('离线'));await context.setOffline(false);await page.locator('.main-nav [data-route="schedule"]').click();await synced();});
 await check('a match past its scheduled start is labelled source-stale and never promoted to live',async()=>{
  const stale=await browser.newContext({viewport:{width:1440,height:900}}),p=await stale.newPage();
  const feed=JSON.parse(JSON.stringify(feeds.cs2)),target=feed.matches.find(m=>m.status==='upcoming'&&m.date);
  assert.ok(target,'cs2 feed publishes an upcoming match');
  target.startsAt=new Date(Date.now()-3600000).toISOString();target.status='upcoming';target.startOverdue=true;
  await p.route('**/api/feed?game=cs2',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(feed)}));
  await p.goto(base+'/schedule');await p.waitForFunction(()=>document.querySelectorAll('.source-chip.ready').length>0,{},{timeout:55000});
  await p.locator('[data-action="pick-date"]').fill(target.date);
  const row=p.locator('.match-row[data-id="'+target.id+'"]');await row.waitFor({timeout:35000});
  assert.equal(await row.getAttribute('data-start-overdue'),'true');
  assert.equal((await row.locator('.match-time small').textContent()).trim(),'应已开赛');
  assert.equal((await row.locator('.status').textContent()).trim(),'未开始','official status is reported unchanged');
  assert.match(await row.getAttribute('title'),/官方仍显示未开始/,'the full explanation is available');
  assert.ok(await p.locator('.match-row:not([data-start-overdue]) .match-time small').first().textContent()==='北京时间','other rows keep the normal time label');
  await stale.close();
 });
 await check('one provider failure is isolated while others keep syncing',async()=>{const broken=await browser.newContext({viewport:{width:1200,height:900}}),p=await broken.newPage();await p.route('**/api/feed?game=valorant',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'官方来源暂时无法读取'})}));await p.goto(base+'/schedule');await p.waitForFunction(()=>document.querySelectorAll('.source-chip.ready').length===3&&document.querySelectorAll('.source-chip.error').length===1,{},{timeout:55000});assert.ok(await p.locator('.match-row').count()>0);assert.ok(!/模拟|录入赛果/.test(await p.locator('body').innerText()));await broken.close();});
 await check('unavailable refresh shows timestamped official cache without pretending to be live',async()=>{await page.route('**/api/feed?game=*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'官方来源暂时无法读取'})}));await page.locator('[data-action="refresh"]').click();await page.waitForFunction(()=>document.querySelectorAll('.source-chip.cached').length===4);assert.ok(await page.locator('.match-row').count()>0);assert.ok((await page.locator('.source-chips').innerText()).includes('更新失败'));await page.unroute('**/api/feed?game=*');});
 await check('service worker excludes data APIs from static cache and offline preserves real snapshots',async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await synced();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await context.setOffline(true);await page.reload();await page.waitForSelector('.match-row');assert.ok((await page.locator('.source-chips').innerText()).includes('缓存'));assert.ok(!(await page.evaluate(async()=>{const names=await caches.keys();const urls=(await Promise.all(names.map(async n=>(await (await caches.open(n)).keys()).map(r=>r.url)))).flat();return urls.some(u=>new URL(u).pathname.startsWith('/api/'));})));await context.setOffline(false);});
 await check('API rejects unsupported input and research files remain inaccessible',async()=>{assert.equal((await fetch(base+'/api/feed?game=other')).status,400);assert.equal((await fetch(base+'/api/standings?event=https://example.com')).status,400);assert.equal((await fetch(base+'/docs/live-cs2.json')).status,404);assert.equal((await fetch(base+'/data/archive/index.json')).status,404);assert.equal((await fetch(base+'/api/archive?game=other')).status,400);assert.equal((await fetch(base+'/api/archive/event?id=https://example.com')).status,400);});
 await check('no uncaught browser errors',async()=>assert.deepEqual(errors,[]));
 await fs.writeFile('docs/browser-verification.json',JSON.stringify({checkedAt:new Date().toISOString(),passed,errors,officialCounts:Object.fromEntries(Object.entries(feeds).map(([g,f])=>[g,f.matches.length]))},null,2));console.log(passed.length+' browser checks passed');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
