import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {eventName,stageName,formatName,localizeEvent,localizeMatch} from '../src/localization.js';
import {parseLolCatalog,parseValorantCatalog,applyChineseNames} from '../server/providers/chinese-names.mjs';
const fixture=JSON.parse(await readFile(new URL('./fixtures/chinese-official-names.json',import.meta.url),'utf8'));
const catalog=game=>({name:'中国赛事官网',url:'https://example.com/public-catalog',status:'ready',retrievedAt:'2026-10-03T07:00:00Z',entries:game==='valorant'?parseValorantCatalog(fixture.valorant):parseLolCatalog('var GameList='+JSON.stringify(fixture.lol)+';')});
const feed=(game,name,year='2026')=>({game,events:[{id:game+':event',game,name}],matches:[{id:game+':match',game,eventId:game+':event',event:name,stage:'Groups',teams:['A','B'],score:null,status:'upcoming',date:year+'-10-03',time:'17:00',startsAt:year+'-10-03T09:00:00Z'}]});
test('Native VCT catalog provides the exact Chinese official tournament name',()=>{const result=applyChineseNames(feed('valorant','Champions · Champions Shanghai'),catalog('valorant'));assert.equal(result.events[0].nameZh,'2026无畏契约全球冠军赛');assert.equal(result.events[0].nameSource.recordId,'1000074');assert.equal(result.events[0].originalName,'Champions · Champions Shanghai');});
test('Native LoL directory resolves the current Demacia tournament and WSCI names',()=>{assert.equal(applyChineseNames(feed('lol','DCGI · 2026'),catalog('lol')).events[0].nameZh,'2026德玛西亚杯');assert.equal(applyChineseNames(feed('lol','WSCI · 2026'),catalog('lol')).events[0].nameZh,'全球挑战者之星邀请赛');});
test('Year mismatches and ambiguous native entries never attach an incorrect official title',()=>{assert.equal(applyChineseNames(feed('valorant','Champions · Champions Shanghai','2027'),catalog('valorant')).events[0].nameZh,undefined);const c=catalog('valorant');c.entries.push({...c.entries[0],id:'different'});assert.equal(applyChineseNames(feed('valorant','Champions · Champions Shanghai'),c).events[0].nameZh,undefined);});
test('Foreign regional competition cannot be mistaken for a native Chinese league',()=>{const result=applyChineseNames(feed('valorant','VCT Americas · Stage 2 2026'),catalog('valorant'));assert.equal(result.events[0].nameZh,undefined);assert.match(localizeEvent(result.events[0]).name,/美洲联赛.*第二赛段/);});
test('LoL JavaScript wrapper is parsed as JSON, never evaluated or accepted with executable trailing code',()=>{assert.throws(()=>parseLolCatalog('var GameList='+JSON.stringify(fixture.lol)+';process.exit(1);'),/格式/);assert.equal(parseLolCatalog('var GameList='+JSON.stringify(fixture.lol)+';').length,2);});
test('All current foreign competitions receive Chinese readable translations',()=>{const examples=[['valorant','Game Changers Championship · 2026','2026 无畏契约改变者全球冠军赛'],['valorant','Game Changers NA · Split 2 2026','2026 无畏契约北美改变者赛 · 第二赛段'],['lol','EMEA Masters · Summer 2026','2026 欧洲、中东及非洲大师赛 · 夏季赛'],['lol','LCS · Split 3 2026','2026 北美职业联赛（LCS） · 第三赛段'],['cs2','ESL Pro League Season 24 2026','2026 ESL 职业联赛第24赛季'],['cs2','StarLadder StarSeries Fall 2026','2026 StarLadder 星系列赛秋季赛'],['apex','Year 6 · Split 2 · Americas','ALGS 第6年 · 分赛2 · 美洲赛区']];for(const[g,en,cn]of examples)assert.equal(eventName(g,en),cn);});
test('Group Stage is never misread as a group letter and Swiss scores are readable',()=>{assert.equal(stageName('Group Stage · 0:0','cs2'),'小组赛 · 0胜0负组');assert.equal(stageName('Groups','valorant'),'小组赛');assert.equal(stageName('Playoffs','lol'),'季后赛');assert.equal(stageName('Playoffs','cs2'),'淘汰赛');assert.equal(stageName('Split 2 Pro League · Group A vs C','apex'),'分赛2职业联赛 · A组对C组');});
test('Official formats and multi-team phase labels are translated without new tournament assumptions',()=>{assert.equal(formatName('single-elim-8'),'8队单败淘汰赛');assert.equal(formatName('swiss-16'),'16队瑞士轮');assert.equal(formatName('BO3'),'BO3');assert.equal(stageName('Match Point Finals · Match Point Finals','apex'),'赛点制决赛');});
test('Localized copies preserve identity, participants, time, results and original titles',()=>{const raw=feed('valorant','Champions · Champions Shanghai');const enriched=applyChineseNames(raw,catalog('valorant'));const event=localizeEvent(enriched.events[0]);const match=localizeMatch(raw.matches[0],event);assert.equal(event.namingType,'official');assert.equal(match.event,'2026无畏契约全球冠军赛');for(const key of ['id','eventId','teams','score','status','date','time','startsAt'])assert.deepEqual(match[key],raw.matches[0][key]);assert.equal(raw.matches[0].event,'Champions · Champions Shanghai');assert.equal(match.originalStage,'Groups');});
test('Unavailable domestic catalogs use a Chinese translation and honestly retain naming provenance',()=>{const result=applyChineseNames(feed('valorant','Champions · Champions Shanghai'),{status:'unavailable',entries:[]});const event=localizeEvent(result.events[0]);assert.equal(event.namingType,'translation');assert.equal(event.name,'2026 无畏契约上海全球冠军赛');assert.equal(event.originalName,'Champions · Champions Shanghai');});

test('Swiss match labels and ALGS bracket rounds use natural Chinese rather than word fragments',()=>{assert.equal(stageName('0-0 Match 3','cs2'),'0胜0负组 · 第3场');assert.equal(stageName('Bracket Stage · Winners Round 1 Lobby A','apex'),'淘汰赛阶段 · 胜者组第1轮 · A组');});
