import {GAME,GAMES} from '../data.js';
import {escape,icon} from '../ui.js';
import {localizeEvent} from '../localization.js';
import {gameSelect} from './schedule.js';
import {bracketDiagram,graphControls} from './bracket.js';
const label=record=>localizeEvent(record.provider?.endsWith('-cn')?{...record,nameZh:record.name}:record,record.year).name;
const date=value=>value?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'日期待核实';
function heading(){return '<section class="page-heading"><div><div class="eyebrow"><span class="tiny-line"></span> THE MATCH ARCHIVE</div><h1>赛事存档<span class="heading-dot">.</span></h1><p>从官方保留的往届记录，重温每一条晋级之路。</p></div><span class="official-label"><i></i> 官方历史数据</span></section>';}
function selectedView(state,payload){const record=payload.record,game=record.game,viewState={...state,bracketGame:game,bracketEvent:record.id,feeds:{[game]:payload.feed},standings:payload.standings?{[record.id]:{...payload.standings,status:'ready'}}:{}},name=label(record);return heading()+(state.archive.error?'<div class="archive-error">'+escape(state.archive.error)+'</div>':'')+'<div class="archive-return"><button class="button secondary" data-action="archive-back">'+icon('left')+'返回存档列表</button><span>已保存至本机 · '+escape(date(payload.archivedAt))+'</span><button class="button secondary" data-action="archive-export">'+icon('download')+'导出存档</button></div><section class="bracket-panel archive-diagram"><div class="bracket-toolbar"><div><span class="archive-game-label">'+escape(GAME(game).name)+' · '+escape(record.year)+'</span><h2>'+escape(name)+'</h2></div>'+(game!=='apex'?graphControls(state):'')+'</div><div class="archive-snapshot-note">'+icon('check')+'<span>'+payload.feed.matches.length+' 场官方比赛 · '+(record.archiveStatus==='partial'?'部分官方数据，未读到的赛果不补写':'已保存官方场次与赛果')+'<small>数据读取：'+escape(new Date(payload.feed.source.retrievedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}))+' · '+escape(payload.feed.source.name)+'</small></span><a href="'+escape(record.sourceUrl||payload.feed.source.url)+'" target="_blank" rel="noopener noreferrer">官方来源 '+icon('arrow')+'</a></div>'+(record.refreshWarning?'<div class="archive-error">'+escape(record.refreshWarning)+'</div>':'')+(payload.feed.warning?'<div class="archive-error">'+escape(payload.feed.warning)+'</div>':'')+bracketDiagram(viewState)+'</section>';}
export function archiveView(state){
 const a=state.archive,index=a.index,selected=a.selected&&a.loaded[a.selected];if(selected)return selectedView(state,selected);
 const records=index?.records||[],years=[...new Set(records.filter(r=>a.game==='all'||r.game===a.game).map(r=>r.year).filter(Boolean))].sort().reverse(),search=state.search.trim().toLowerCase();
 const filtered=records.filter(r=>(a.game==='all'||r.game===a.game)&&(a.year==='all'||r.year===a.year)&&(a.filter==='all'||a.filter==='saved'&&r.archivedAt||a.filter==='unavailable'&&r.archiveStatus==='unavailable')&&(!search||[label(r),r.name,r.originalName,r.year,GAME(r.game).name].some(t=>String(t||'').toLowerCase().includes(search)))),pages=Math.max(1,Math.ceil(filtered.length/24));a.page=Math.min(a.page,pages-1);const list=filtered.slice(a.page*24,(a.page+1)*24),progress=index?.progress;
 const coverage='<details class="archive-coverage"><summary>'+icon('globe')+'官方覆盖范围与读取状态 '+icon('chevron')+'</summary>'+GAMES.map(g=>{const source=index?.sources?.[g.id],own=records.filter(r=>r.game===g.id),range=[...new Set(own.map(r=>r.year).filter(Boolean))].sort();return '<div><b>'+escape(g.name)+'</b><p>'+escape(source?.coverage||'正在读取官方历史目录')+'</p><small>'+(range.length?'目录范围 '+range[0]+'—'+range.at(-1)+' · '+own.length+' 项赛事':'暂未读到历史目录')+' · 已存档 '+own.filter(r=>r.archivedAt).length+'</small>'+(source?.error?'<p class="source-warning">'+escape(source.error)+'</p>':'')+'</div>';}).join('')+'<p>官网当前未保留的首届或更早记录暂不能补齐；目录有名称但无可读赛果的赛事会明确标记。</p></details>';
 return heading()+'<section class="archive-panel"><div class="archive-status"><div><span class="archive-status-icon">'+icon('trophy')+'</span><span><b>'+(progress?.saved||0)+' <small>项已存档</small></b><p>'+(progress?.discovering?'正在更新官方历史目录':progress?.running?'正在补全历史赛事 · 待读取 '+(progress.pending+progress.active)+' 项':'官方历史目录 '+records.length+' 项 · 自动保存新结束的赛事')+'</p></span></div><button class="button secondary compact" data-action="archive-sync" '+(a.status==='syncing'?'disabled':'')+'>'+icon('refresh')+(a.status==='syncing'?'同步中…':'同步存档')+'</button></div>'+coverage+'<div class="archive-filters">'+gameSelect(a.game,'archive-game')+'<label class="archive-year">'+icon('calendar')+'<select aria-label="选择存档年份" data-archive-filter="year"><option value="all">全部年份</option>'+years.map(y=>'<option value="'+escape(y)+'" '+(y===a.year?'selected':'')+'>'+escape(y)+' 年</option>').join('')+'</select></label><div class="archive-filter-tabs">'+[['all','全部记录'],['saved','已存档'],['unavailable','暂不可读']].map(([value,text])=>'<button data-action="archive-filter" data-filter="'+value+'" class="'+(a.filter===value?'selected':'')+'">'+text+'</button>').join('')+'</div><span class="archive-result-count">'+filtered.length+' 项赛事</span></div>'+(a.error?'<div class="archive-error">'+escape(a.error)+'</div>':'')+(a.loadingId?'<div class="archive-loading">'+icon('refresh')+'正在读取官方历史赛事，保存成功后打开晋级图…</div>':'')+(a.status==='loading'&&!index?'<div class="empty-state"><h3>正在读取官方历史目录</h3><p>四款游戏独立同步，成功读取的数据会保留在本机。</p></div>':list.length?'<div class="archive-grid">'+list.map(r=>'<button class="archive-event-card" style="--game:'+GAME(r.game).color+'" data-action="archive-open" data-event="'+escape(r.id)+'" '+(a.loadingId?'disabled':'')+'><div class="archive-event-meta"><span style="--game:'+GAME(r.game).color+'">'+escape(GAME(r.game).name)+'</span><small>'+escape(r.year)+'</small></div><h3>'+escape(label(r))+'</h3><p>'+escape(date(r.startsAt))+' — '+escape(date(r.endsAt))+'</p><div class="archive-event-bottom"><span class="archive-badge '+escape(r.archiveStatus)+'">'+(r.archiveStatus==='saved'?'已存档':r.archiveStatus==='partial'?'部分数据已存档':r.archiveStatus==='unavailable'?'官方数据暂不可读':r.archiveStatus==='loading'?'正在存档':'等待存档')+'</span><span>'+(r.matchCount?r.matchCount+' 场比赛':'读取官方对阵')+' '+icon('right')+'</span></div></button>').join('')+'</div>':'<div class="empty-state"><h3>没有符合筛选条件的赛事</h3><p>可切换游戏、年份或搜索名称。</p></div>')+'<div class="archive-pagination"><button data-action="archive-page" data-offset="-1" '+(a.page===0?'disabled':'')+'>'+icon('left')+'上一页</button><span>'+(a.page+1)+' / '+pages+'</span><button data-action="archive-page" data-offset="1" '+(a.page===pages-1?'disabled':'')+'>下一页'+icon('right')+'</button></div></section>';
}
