import {stageName,formatName} from '../localization.js';
import {GAME,TEAMS} from '../data.js';
import {getMatches,getEvents,nearestEvent} from '../state.js';
import {escape,icon} from '../ui.js';
import {badge,teamName,statusLabel} from '../components.js';
import {gameSelect,eventSelect} from './schedule.js';
import {sourcePanel} from '../sources.js';
import {layoutBracket} from '../bracket.js';
import {layoutElimination} from '../elimination.js';
import {layoutSwiss,layoutStageMap,layoutStageCards} from '../mindmap.js';
function card(m,style=''){return '<button class="official-match-card '+(m.winner?'completed':'')+'" data-match-status="'+escape(m.status||'unknown')+'" data-action="detail" data-id="'+escape(m.id)+'" '+(style?'style="'+style+'"':'')+'><div class="official-card-meta"><span>'+escape(m.matchName||m.stage)+'</span>'+statusLabel(m.status)+'</div>'+[0,1].map(i=>'<div class="official-team-line '+(m.winner&&m.winner===m.teams[i]?'winner':'')+'">'+badge(m.teams[i])+'<span>'+teamName(m.teams[i])+'</span><b>'+(m.score?m.score[i]:'—')+'</b></div>').join('')+'<small>'+m.date+' · '+m.time+' · '+escape(m.format)+'</small></button>';}
function graph(matches,state){const graph=layoutBracket(matches);return '<div class="bracket-scroll"><div class="bracket-sizer" style="width:'+graph.width*state.zoom+'px;height:'+graph.height*state.zoom+'px"><div class="official-canvas" data-graph-width="'+graph.width+'" data-graph-height="'+graph.height+'" style="width:'+graph.width+'px;height:'+graph.height+'px;transform:scale('+state.zoom+')">'+graph.columns.map((c,i)=>'<div class="round-label" style="left:'+(26+i*310)+'px"><span>'+String(i+1).padStart(2,'0')+'</span>'+escape(c[0]?.matchName?.replace(/ \d+$/,'')||'官方对阵')+'</div>').join('')+'<svg class="bracket-lines" viewBox="0 0 '+graph.width+' '+graph.height+'" aria-hidden="true">'+graph.edges.map(edge=>{const a=graph.positions[edge.from],b=graph.positions[edge.to];return '<path d="M'+(a.x+256)+' '+(a.y+75)+' H'+(a.x+283)+' V'+(b.y+75)+' H'+b.x+'" data-edge-kind="official-advancement" class="'+(edge.advanced?'advanced':'')+'"/>';}).join('')+'</svg>'+graph.nodes.map(m=>card(m,'position:absolute;left:'+graph.positions[m.id].x+'px;top:'+graph.positions[m.id].y+'px;width:256px')).join('')+'</div></div></div>';}
function shortTeam(id){return id?teamName(id):'待官方公布';}
function miniMatch(m){const title=m.teams.map(id=>TEAMS[id]?.short||'待官方公布').join(' 对阵 ')+' · '+m.date+' '+m.time;return '<button class="map-match '+(m.status==='live'?'is-live':'')+'" data-match-status="'+escape(m.status||'unknown')+'" data-action="detail" data-id="'+escape(m.id)+'" aria-label="'+escape(title)+'" title="'+escape(title)+'"><span class="map-team '+(m.winner===m.teams[0]&&m.winner?'winner':'')+'">'+badge(m.teams[0])+'<span>'+shortTeam(m.teams[0])+'</span></span><b class="map-score">'+(m.score?m.score.join(':'):'vs')+'</b><span class="map-team '+(m.winner===m.teams[1]&&m.winner?'winner':'')+'">'+badge(m.teams[1])+'<span>'+shortTeam(m.teams[1])+'</span></span>'+(m.status==='live'?'<i class="map-live-dot" title="正在比赛"></i>':'')+'</button>';}
function mapNode(node,game){const position='left:'+node.x+'px;top:'+node.y+'px;width:'+node.width+'px;height:'+node.height+'px';if(node.kind==='root')return '<div class="map-node map-root" style="'+position+'"><span class="map-root-icon">'+icon('trophy')+'</span><small>赛事中心</small><h3>'+escape(node.name)+'</h3><p>官方阶段与已公布对阵</p></div>';if(node.kind==='qualified'||node.kind==='eliminated'){const qualified=node.kind==='qualified';return '<section class="map-node map-outcome '+node.kind+'" data-outcome="'+node.kind+'" style="'+position+'"><div class="map-outcome-title">'+icon(qualified?'trophy':'bracket')+'<h4>'+(qualified?'晋级名单':'止步本阶段')+'</h4></div><p>官方'+(qualified?'晋级':'淘汰')+'名额 <b>'+node.count+'</b> <span>· 已确定 '+node.teams.length+'</span></p>'+(node.teams.length?'<div class="map-outcome-teams">'+node.teams.map(id=>'<span title="'+escape(TEAMS[id]?.name||id)+'">'+badge(id)+'<b>'+teamName(id)+'</b></span>').join('')+'</div>':'<div class="map-outcome-empty">'+icon('clock')+'等待官方赛果</div>')+'</section>';}
const done=node.matches.filter(m=>m.status==='finished').length,dates=[...new Set(node.matches.map(m=>m.date))],dateLabel=dates.length===1?dates[0].slice(5).replace('-','月')+'日':'赛程已公布';return '<section class="map-node map-group" data-group="'+escape(node.name)+'" style="'+position+'"><div class="map-group-heading"><div><small>'+(node.wins===0&&node.losses===0?'初始对阵':node.wins!=null?'胜负分组':'官方阶段')+'</small><h4>'+escape(stageName(node.name,game))+'</h4></div><span>'+node.matches.length+' 场</span></div><div class="map-matches">'+node.matches.map(miniMatch).join('')+'</div><div class="map-group-footer"><span>'+escape(dateLabel)+'</span><span>'+done+'/'+node.matches.length+' 已结束</span></div></section>';}
function pathFor(edge,model){const a=model.nodes.find(n=>n.id===edge.from),b=model.nodes.find(n=>n.id===edge.to),ax=a.x+a.width,ay=a.y+a.height/2,bx=b.x,by=b.y+b.height/2;if(edge.terminal&&b.column-a.column>1){const lane=edge.outcome==='win'?model.top-32:model.bottom+32;return 'M'+ax+' '+ay+' H'+(ax+20)+' V'+lane+' H'+(bx-24)+' V'+by+' H'+bx;}const mid=(ax+bx)/2;return 'M'+ax+' '+ay+' C'+mid+' '+ay+' '+mid+' '+by+' '+bx+' '+by;}
function mindmap(model,state,game){return '<div class="mindmap-scroll bracket-scroll" tabindex="0" aria-label="'+(model.type==='swiss'?'瑞士轮分组路径图':'赛事阶段思维导图')+'，可横向滚动"><div class="bracket-sizer" style="width:'+model.width*state.zoom+'px;height:'+model.height*state.zoom+'px"><div class="official-canvas mindmap-canvas '+model.type+'" data-graph-width="'+model.width+'" data-graph-height="'+model.height+'" style="width:'+model.width+'px;height:'+model.height+'px;transform:scale('+state.zoom+')">'+(model.type==='swiss'?model.columns.map((c,i)=>'<div class="map-column-label" style="left:'+(28+i*model.columnWidth)+'px"><span>'+String(i+1).padStart(2,'0')+'</span>第'+(i+1)+'轮</div>').join('')+'<div class="map-column-label" style="left:'+(28+model.columns.length*model.columnWidth)+'px"><span>↗</span>阶段结果</div>':'')+'<svg class="mindmap-lines" width="'+model.width+'" height="'+model.height+'" viewBox="0 0 '+model.width+' '+model.height+'" aria-hidden="true">'+model.edges.map(edge=>'<path class="'+edge.kind+' '+(edge.outcome||'')+'" data-edge-kind="'+edge.kind+'" data-from="'+escape(edge.from)+'" data-to="'+escape(edge.to)+'" d="'+pathFor(edge,model)+'"><title>'+(edge.kind==='membership'?'阶段包含对阵':edge.outcome==='win'?'获胜后的分组路径，对手以官方公布为准':'失利后的分组路径，对手以官方公布为准')+'</title></path>').join('')+model.edges.filter(e=>e.kind==='group-flow'&&!e.terminal).map(edge=>{const a=model.nodes.find(n=>n.id===edge.from);return '<g class="map-edge-label '+edge.outcome+'" transform="translate('+(a.x+a.width+12)+','+(a.y+a.height/2+(edge.outcome==='win'?-14:24))+')"><rect x="-8" y="-12" width="30" height="19" rx="5"/><text>'+ (edge.outcome==='win'?'胜':'负')+'</text></g>';}).join('')+'</svg>'+model.nodes.map(node=>mapNode(node,game)).join('')+'</div></div></div>';}
function csBoard(state,matches){const stages=(state.feeds.cs2?.brackets||[]).filter(b=>b.eventId===state.bracketEvent);if(!stages.length)return grouped(matches,state);return stages.map(stage=>{const ids=new Set(stage.groups.flatMap(g=>g.matchIds)),nodes=matches.filter(m=>ids.has(m.id)),linked=nodes.some(m=>m.nextMatch&&ids.has(m.nextMatch)),swiss=layoutSwiss(stage,nodes);return '<section class="official-stage"><div class="official-stage-title"><h3>'+escape(stageName(stage.name,'cs2'))+'</h3><span>'+escape(formatName(stage.format||'官方赛制'))+'</span></div>'+(swiss?'<div class="map-description"><span><i class="map-legend-line win"></i>获胜路径</span><span><i class="map-legend-line loss"></i>失利路径</span><p>按官方胜负分组绘制 · 虚线表示分组流向，对手由官方重新配对</p></div>'+mindmap(swiss,state,'cs2'):linked?'<div class="map-description"><span><i class="map-legend-line official"></i>官方下一场对阵</span><p>沿官方晋级关系连接，赛果公布后自动更新队伍</p></div>'+graph(nodes,state):'<div class="map-description"><span><i class="map-legend-line"></i>阶段包含对阵</span><p>官方未公布下一场关系时，按真实阶段连接展示</p></div>'+mindmap(layoutStageMap({name:stageName(stage.name,'cs2')},stage.groups,nodes),state,'cs2'))+'</section>';}).join('');}
function largeCard(node){const m=node.match;return '<button class="duel-card" data-match-status="'+escape(m.status||'unknown')+'" data-action="detail" data-id="'+escape(m.id)+'" style="left:'+node.x+'px;top:'+node.y+'px;width:'+node.width+'px;height:'+node.height+'px"><div class="duel-card-meta"><span>'+escape(m.matchName||m.roundName||m.stage)+'</span>'+statusLabel(m.status)+'</div><div class="duel-card-teams">'+[0,1].map((i)=>'<div class="duel-opponent '+(m.winner&&m.winner===m.teams[i]?'winner':'')+'">'+badge(m.teams[i])+'<strong title="'+escape(TEAMS[m.teams[i]]?.name||'待官方公布')+'">'+teamName(m.teams[i])+'</strong></div>'+(i===0?'<div class="duel-versus"><b>'+(m.score?m.score.join(' : '):'VS')+'</b><small>'+escape(m.format)+'</small></div>':'')).join('')+'</div><div class="duel-card-footer"><span>'+escape(m.date)+' · '+escape(m.time)+'</span><span>查看比赛 '+icon('right')+'</span></div></button>';}
function stageCardGraph(name,matches,state,layout){
 const model=layout||layoutStageCards(name,matches),root=model.nodes[0],elimination=model.type==='elimination',nodes=new Map(model.nodes.map(n=>[n.id,n]));
 const paths=model.edges.map(edge=>{
  const a=nodes.get(edge.from),b=nodes.get(edge.to);let path;
  if(!elimination){const rail=b.x-22;path='M'+(root.x+root.width)+' '+(root.y+80)+' H282 V78 H'+rail+' V'+(b.y+b.height/2)+' H'+b.x;}
  else if(b.column-a.column>1){const lane=edge.outcome==='loss'&&b.lane==='lower'?model.lowerTop-76:78;path='M'+(a.x+a.width)+' '+(a.y+a.height/2)+' H'+(a.x+a.width+24)+' V'+lane+' H'+(b.x-24)+' V'+(b.y+b.height/2)+' H'+b.x;}
  else path=pathFor(edge,model);
  const label=edge.kind==='stage-entry'?'赛事入口：首轮比赛':edge.kind==='membership'?'该阶段包含的比赛':(TEAMS[edge.teamId]?.short||'队伍')+' · '+(edge.outcome==='loss'?'失利后进入下一场':'获胜后进入下一场');
  return '<path class="'+edge.kind+' '+(edge.outcome||'')+'" data-edge-kind="'+edge.kind+'" data-from="'+escape(edge.from)+'" data-to="'+escape(edge.to)+'"'+(edge.outcome?' data-outcome="'+edge.outcome+'"':'')+(edge.teamId?' data-team-id="'+escape(edge.teamId)+'"':'')+' d="'+path+'"><title>'+escape(label)+'</title></path>';
 }).join('');
 const labels=elimination?model.rounds.map(r=>'<div class="elimination-round-label '+r.lane+'" style="left:'+r.x+'px;top:'+r.y+'px">'+escape(stageName(r.name,state.bracketGame))+'</div>').join(''):'';
 return '<div class="bracket-scroll stage-card-scroll" tabindex="0" aria-label="'+escape(name)+(elimination?'逐轮晋级图':'独立比赛对阵图')+'"><div class="bracket-sizer"><div class="official-canvas stage-card-canvas '+(elimination?'elimination-canvas':'')+'" data-graph-width="'+model.width+'" data-graph-height="'+model.height+'" style="width:'+model.width+'px;height:'+model.height+'px;transform:scale('+state.zoom+')"><svg class="mindmap-lines" width="'+model.width+'" height="'+model.height+'" aria-hidden="true">'+paths+'</svg>'+labels+mapNode(root,state.bracketGame)+model.nodes.filter(n=>n.kind==='match').map(largeCard).join('')+'</div></div></div>';
}
function grouped(matches,state){
 const groups=new Map();for(const m of matches){if(!groups.has(m.stage))groups.set(m.stage,[]);groups.get(m.stage).push(m);}
 const promotions=state.feeds[state.bracketGame]?.promotions||[];
 return '<div class="official-topology-note">'+icon('link')+'淘汰赛按官方轮次展开，连线展示官方晋级关系或已确认的赛果路径。不推测晋级对手；其他阶段虚线表示所属比赛。</div>'+[...groups].map(([name,list])=>{
  const promotion=promotions.find(p=>p.promotionName===name),model=layoutElimination(name,list,promotion);
  return '<section class="official-stage"><div class="official-stage-title"><h3>'+escape(name)+'</h3><span>'+list.length+' 场官方对阵</span></div>'+(model?'<div class="map-description"><span><i class="map-legend-line win"></i>获胜晋级</span><span><i class="map-legend-line loss"></i>失利后的路径</span><p>赛事入口连接首轮 · 决赛在最右侧 · 下一场参赛队以官方公布为准</p></div>':'')+stageCardGraph(name,list,state,model)+'</section>';
 }).join('');
}
function apexBoard(state){const data=state.standings[state.bracketEvent];if(!data||data.status==='loading')return '<div class="empty-state">'+icon('refresh')+'<h3>正在读取 ALGS 官方积分</h3><p>排名与晋级状态以 EA 公布的数据为准。</p></div>';if(data.status==='error')return '<div class="empty-state"><h3>官方积分暂时无法读取</h3><p>'+escape(data.error)+'</p><button class="button secondary" data-action="refresh">重新读取</button></div>';return '<div class="official-topology-note">'+icon('trophy')+'积分、排名与已晋级标记均来自 ALGS 官方；未标记晋级不代表淘汰。'+(data.stale?' 当前显示上次读取的缓存。':'')+'</div>'+data.phases.map(p=>'<section class="official-stage"><div class="official-stage-title"><h3>'+escape(stageName(p.name,'apex'))+'</h3><span>官方积分 · '+new Date(data.retrievedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+'</span></div>'+(p.rows.length?'<div class="apex-table-wrap"><div class="apex-table-head"><span>排名</span><span>战队</span><span>击杀</span><span>已赛组次</span><span>总积分</span><span>晋级状态</span></div>'+p.rows.map(t=>'<div class="apex-team-row '+(t.qualified?'qualifying':'')+'"><span class="rank-number '+(t.position<=3?'top':'')+'">'+t.position+'</span><span class="apex-team-name">'+badge(t.id)+'<b>'+teamName(t.id)+'</b></span><span>'+(t.kills??'—')+'</span><span>'+(t.played??'—')+'</span><strong>'+(t.points??'—')+'</strong><span class="qualification">'+(t.qualified?icon('check')+'已晋级':'未公布晋级')+'</span></div>').join('')+'</div>':'<div class="empty-mini">本阶段官方尚未公布积分</div>')+'</section>').join('')+(!data.phases.length?'<div class="empty-state"><h3>官方尚未公布积分</h3><p>可切换赛事，查看已完成阶段。</p></div>':'')+(data.partial?'<p class="source-warning">部分阶段暂时不可读，稍后更新重试。</p>':'');}
export function bracketView(state){const events=getEvents(state.bracketGame,state.feeds);if(!events.some(e=>e.id===state.bracketEvent))state.bracketEvent=nearestEvent(state.bracketGame)||null;const selected=events.find(e=>e.id===state.bracketEvent),matches=getMatches(state.feeds).filter(m=>m.eventId===state.bracketEvent),apex=state.bracketGame==='apex';return '<section class="page-heading"><div><div class="eyebrow"><span class="tiny-line"></span> THE ROAD TO GLORY</div><h1>晋级之路<span class="heading-dot">.</span></h1><p>官方赛果自动同步，跟随每一步晋级。</p></div><span class="official-label"><i></i> 官方对阵</span></section>'+sourcePanel(state,state.bracketGame)+'<section class="bracket-panel"><div class="bracket-toolbar"><div class="filter-selects">'+gameSelect(state.bracketGame,'bracket-game')+eventSelect(state,true)+'</div>'+(!apex?'<div class="graph-view-controls"><button class="graph-fit-button" data-action="zoom-fit">总览</button><div class="zoom-controls"><button data-action="zoom" data-step="-0.1" aria-label="缩小对阵图">−</button><span data-zoom-label>'+Math.round(state.zoom*100)+'%</span><button data-action="zoom" data-step="0.1" aria-label="放大对阵图">＋</button></div></div>':'')+'</div><div class="bracket-summary"><div><span class="event-badge">'+icon('trophy')+'</span><span><h2>'+escape(selected?.name||'正在读取官方赛事')+'</h2><p>'+escape(GAME(state.bracketGame).name)+' · '+(apex?'官方积分排名':'已公布 '+matches.length+' 场对阵')+'</p></span></div></div><div class="bracket-help"><span>'+icon('link')+'点击比赛查看详情 · 拖动空白处移动</span><span><i class="purple-dot"></i>官方赛果 <i class="gray-dot"></i>待官方公布</span></div>'+(selected?(apex?apexBoard(state):state.bracketGame==='cs2'?csBoard(state,matches):grouped(matches,state)):'<div class="empty-state"><h3>'+ (state.sources[state.bracketGame].status==='error'?'官方来源暂时不可读':'正在读取官方赛程')+'</h3><p>读取成功后将展示官网已公布的对阵。</p></div>')+'</section><footer class="page-footer"><span><span class="brand-mini">↗</span> 每一场热爱，都有赛点。</span><span>只读官方赛果 · 自动更新</span></footer>';}

export function bracketDiagram(state){const matches=getMatches(state.feeds).filter(m=>m.eventId===state.bracketEvent);return state.bracketGame==='apex'?apexBoard(state):state.bracketGame==='cs2'?csBoard(state,matches):grouped(matches,state);}
export function graphControls(state){return '<div class="graph-view-controls"><button class="graph-fit-button" data-action="zoom-fit">总览</button><div class="zoom-controls"><button data-action="zoom" data-step="-0.1" aria-label="缩小对阵图">−</button><span data-zoom-label>'+Math.round(state.zoom*100)+'%</span><button data-action="zoom" data-step="0.1" aria-label="放大对阵图">＋</button></div></div>';}
