import {publicFetch,clock,team,finish} from './common.mjs';
import {decodeBlast,normalizeBlast} from './blast.mjs';
import {chineseCatalog} from './chinese-names.mjs';
import {API,normalizeApex,apexStandings} from './apex.mjs';
export const VAL='https://val.native.game.qq.com/esports/v1/data/';
export const LOL_QUERY='https://apps.game.qq.com/lol/match/apis/searchBMatchInfo_bak.php';
export function parseAssignment(script,name){const match=String(script).match(/^\s*(?:var\s+)?([A-Za-z_$][\w$]*)\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);if(!match||match[1]!==name)throw new Error('官方数据包装已变更');return JSON.parse(match[2]);}
export const iso=value=>{if(!value||/^0000/.test(value))return null;const str=String(value),d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(str)?str+'T23:59:59+08:00':str);return Number.isFinite(+d)?d.toISOString():null;};
export function historyRecord(game,provider,id,name,start,end,extra={}){const startsAt=iso(start),endsAt=iso(end),date=startsAt||endsAt,year=date?new Date(Date.parse(date)+8*3600000).getUTCFullYear().toString():String(extra.year||'');return {id:game+':'+(provider.endsWith('-cn')?'cn:':'')+id,game,provider,nativeId:String(id),name,startsAt,endsAt,...extra,year};}
export const past=r=>r.endsAt?Date.parse(r.endsAt)<Date.now():/^20\d{2}$/.test(r.year)&&Number(r.year)<new Date().getUTCFullYear();
export async function discoverHistory(game){
 let records,source;
 if(game==='cs2'){const page=decodeBlast(await publicFetch('https://blast.tv/cs/tournaments')),list=page.loaderData?.['routes/$gameId.tournaments._index'];if(!list)throw new Error('BLAST 历史目录结构已变更');records=Object.values(list.groupedFinishedTournaments||{}).flat().map(t=>historyRecord(game,'blast',t.id,t.name,t.startDate,t.endDate,{sourceUrl:'https://blast.tv/cs/tournaments/'+t.id}));source={name:'BLAST 官方赛事目录',url:'https://blast.tv/cs/tournaments',coverage:'BLAST 官网当前保留的 CS 历史赛事；早期包含 CS:GO，不代表全部首届至今赛事'};}
 else if(game==='valorant'){const payload=await publicFetch(VAL+'VAL_SGameList.json',true);if(!Array.isArray(payload.msg))throw new Error('无畏契约历史目录已变更');records=payload.msg.filter(e=>e.secondLevelGameId&&e.secondLevelGameName&&!/测试|test/i.test(e.secondLevelGameName)).map(e=>historyRecord(game,'valorant-cn',e.secondLevelGameId,e.secondLevelGameName,e.sDate,e.eDate,{year:e.gameYear,originalName:e.secondLevelGameEnName||e.secondLevelGameName,sourceUrl:'https://vct.qq.com/',officialStatus:e.gameStatusId}));source={name:'无畏契约中国官方赛事目录',url:VAL+'VAL_SGameList.json',coverage:'中国官方目录当前保留的历届赛事；早于目录覆盖范围的首届记录暂不可读'};}
 else if(game==='lol'){const catalog=await chineseCatalog('lol');if(!catalog.entries.length)throw new Error('英雄联盟官方目录暂不可读');records=catalog.entries.filter(e=>!/测试专用/i.test(e.name)).map(e=>historyRecord(game,'lol-cn',e.id,e.name,e.startsAt,e.endsAt,{year:e.year,catalogYear:e.year,sourceUrl:'https://lpl.qq.com/es/schedule.shtml'}));source={name:'英雄联盟中国官方赛事目录',url:catalog.url,coverage:'中国官方目录当前保留的国内及国际赛事；未保留的更早首届比赛暂不可读'};}
 else if(game==='apex'){const seasons=await publicFetch(API+'/seasons',true);const list=Array.isArray(seasons)?seasons:seasons.seasons;if(!Array.isArray(list))throw new Error('ALGS 历史赛季结构已变更');const responses=await Promise.allSettled(list.filter(s=>Date.parse(s.startDate)<Date.now()).map(async season=>{const payload=await publicFetch(API+'/series/seasons/'+season.id,true);if(!Array.isArray(payload.series))throw new Error('ALGS 历史赛程未公布');const feed=normalizeApex(payload.series,season);return feed.events.map(event=>{const matches=feed.matches.filter(m=>m.eventId===event.id);return historyRecord(game,'algs',event.id.slice(5),event.name,matches[0]?.startsAt,matches.at(-1)?.startsAt,{sourceUrl:event.sourceUrl,seasonId:season.id,seasonName:season.name,phases:event.phases,officialCompleted:matches.length>0&&matches.every(m=>['finished','cancelled'].includes(m.status))});});}));records=responses.filter(r=>r.status==='fulfilled').flatMap(r=>r.value);if(!records.length)throw new Error('ALGS 历史数据暂不可读');source={name:'EA · ALGS 官方历史数据',url:API+'/seasons',coverage:'ALGS 官方接口当前保留的赛季和赛区；未保留的更早首届比赛暂不可读',partial:responses.some(r=>r.status==='rejected')};}
 else throw new Error('不支持的游戏');
 return {game,source:{...source,retrievedAt:new Date().toISOString()},records:[...new Map(records.filter(r=>r.provider==='algs'?r.officialCompleted:r.provider==='valorant-cn'&&r.officialStatus!=null?r.officialStatus===3:past(r)).map(r=>[r.id,r])).values()]};
}
const status=value=>({1:'upcoming',2:'live',3:'finished'}[Number(value)]||'unknown');
const number=value=>/^\d+$/.test(String(value))?Number(value):null;
export function normalizeNativeValorant(record,payload,info,promotions={msg:[]}){
 if(!Array.isArray(payload.msg))throw new Error('官方历史对阵尚未公布');const teams={},teamById=new Map((info.msg?.teams||[]).map(t=>[String(t.teamId),t])),rounds=new Map();
 for(const p of promotions.msg||[])for(const [roundIndex,r]of (p.promotionData||[]).entries())for(const [index,s]of (r.sessions||[]).entries())rounds.set(String(s.bMatchId),{stage:p.promotionName,roundName:r.des,index:roundIndex*100+index});
 const matches=payload.msg.filter(m=>String(m.secondLevelGameId)===record.nativeId).map(m=>{const own=rounds.get(String(m.bMatchId)),s=status(m.matchStatusId),ts=['A','B'].map(side=>{const t=m['team'+side]||teamById.get(String(m['team'+side+'Id']));return t?team('cn:'+t.teamId,{...t,id:'cn:'+t.teamId,name:t.teamName,shortName:t.teamShortName||t.teamSpName||t.teamName},'valorant',teams):null;}),scores=[number(m.scoreA),number(m.scoreB)],score=['live','finished'].includes(s)&&scores.every(x=>x!==null)?scores:null;return {id:'valorant:cn:'+m.bMatchId,game:'valorant',eventId:record.id,event:record.name,stage:own?.stage||[m.matchType,m.groupName].filter(Boolean).join(' · ')||'官方阶段',matchName:m.bMatchName,roundName:own?.roundName,index:own?.index,format:m.matchFormat||'赛制待公布',...clock(m.matchDate),status:s,teams:ts,score,winner:s==='finished'&&score&&score[0]!==score[1]?ts[score[0]>score[1]?0:1]:null,sourceUrl:'https://vct.qq.com/'};});
 return finish('valorant','无畏契约中国赛事官网','https://vct.qq.com/',matches,teams,[{...record,nameZh:record.name,topologyPublished:false}],{promotions:promotions.msg||[],coverage:'该赛事官方完整场次目录；晋级关系仅按官网已公布内容展示'});
}
export function normalizeNativeLol(record,rows,teamList){const teams={};const matches=rows.filter(m=>String(m.GameId)===record.nativeId).map((m,i)=>{const s=status(m.MatchStatus),ts=['A','B'].map(side=>{const t=teamList[String(m['Team'+side])];return t?team('cn:'+t.TeamId,{...t,id:'cn:'+t.TeamId,name:t.TeamName,shortName:t.TeamShortName||t.TeamName},'lol',teams):null;}),scores=[number(m.ScoreA),number(m.ScoreB)],score=['live','finished'].includes(s)&&scores.every(x=>x!==null)?scores:null;return {id:'lol:cn:'+m.bMatchId,game:'lol',eventId:record.id,event:record.name,stage:m.GameTypeName||'官方阶段',roundName:m.GameProcName,matchName:m.bMatchName,index:i,format:'赛制以官方页面为准',...clock(m.MatchDate?String(m.MatchDate).replace(' ','T')+'+08:00':null),status:s,teams:ts,score,winner:s==='finished'&&['1','2'].includes(String(m.MatchWin))?ts[Number(m.MatchWin)-1]:null,sourceUrl:'https://lpl.qq.com/es/schedule.shtml'};});return finish('lol','英雄联盟中国赛事官网','https://lpl.qq.com/es/schedule.shtml',matches,teams,[{...record,nameZh:record.name,topologyPublished:false}],{coverage:'该赛事官方历史查询，已遍历所有分页；官网未提供的晋级连接不推测'});}
let lolTeams=null,lolTeamsAt=0,lolTeamPending=null;const seasonFeeds=new Map();
async function readLolTeams(){if(lolTeams&&Date.now()-lolTeamsAt<3600000)return lolTeams;if(!lolTeamPending)lolTeamPending=publicFetch('https://lpl.qq.com/web201612/data/LOL_MATCH2_TEAM_LIST.js').then(raw=>{lolTeams=parseAssignment(raw,'TeamList').msg;lolTeamsAt=Date.now();return lolTeams;}).finally(()=>lolTeamPending=null);return lolTeamPending;}
export async function fetchHistory(record){
 let feed,standings=null;
 if(record.provider==='blast'){const data=decodeBlast(await publicFetch('https://blast.tv/cs/tournaments/'+record.nativeId)),detail=data.loaderData?.['routes/$gameId.tournaments.$tournamentId'];if(!detail?.tournamentBracketsPromise)throw new Error('官方已移除该赛事对阵');feed=normalizeBlast([detail]);}
 else if(record.provider==='valorant-cn'){const data=await Promise.allSettled([publicFetch(VAL+'VAL_Match_'+record.nativeId+'.json',true),publicFetch(VAL+'VAL_Game_'+record.nativeId+'.json',true),publicFetch(VAL+'VAL_GAME_'+record.nativeId+'_promotion.json',true)]);if(data[0].status==='rejected')throw new Error('官方暂未提供该赛事历史对阵');const info=data[1].status==='fulfilled'?data[1].value:{msg:{teams:[]}};const known=new Set((info.msg?.teams||[]).map(t=>String(t.teamId))),missing=[...new Set(data[0].value.msg.flatMap(m=>[m.teamAId,m.teamBId]).filter(Boolean).map(String))].filter(id=>!known.has(id)&&!data[0].value.msg.some(m=>String(m.teamAId)===id&&m.teamA||String(m.teamBId)===id&&m.teamB));for(let i=0;i<missing.length;i+=3){const found=await Promise.allSettled(missing.slice(i,i+3).map(async id=>{const p=await publicFetch(VAL+'VAL_Team_'+id+'.json',true);return p.msg;}));for(const r of found)if(r.status==='fulfilled'&&r.value?.teamId)(info.msg.teams||=[]).push(r.value);}feed=normalizeNativeValorant(record,data[0].value,info,data[2].status==='fulfilled'?data[2].value:{msg:[]});}
 else if(record.provider==='lol-cn'){const pageUrl=page=>LOL_QUERY+'?p1='+record.nativeId+'&p6=1&page='+page+'&pagesize=250&r1=retObj';const first=parseAssignment(await publicFetch(pageUrl(1)),'retObj');if(String(first.status)!=='0'||!Array.isArray(first.msg?.result))throw new Error('官方未提供该赛事历史比赛');const rows=[...first.msg.result],pages=Number(first.msg.totalpage||1),total=Number(first.msg.total),warnings=[];if(!Number.isInteger(pages)||pages<1||pages>500)throw new Error('官方分页数量无法核实');for(let p=2;p<=pages;p++){try{const page=parseAssignment(await publicFetch(pageUrl(p)),'retObj');if(!Array.isArray(page.msg?.result))throw new Error('官方历史分页暂不可读');rows.push(...page.msg.result);}catch{warnings.push('第'+p+'页暂不可读');}}const unique=[...new Map(rows.map(m=>[String(m.bMatchId),m])).values()];if(unique.length!==total)warnings.push('官方报告 '+total+' 场，实际可读 '+unique.length+' 场');feed=normalizeNativeLol(record,unique,await readLolTeams());if(warnings.length){feed.partial=true;feed.warning=warnings.join('；');feed.expectedMatchCount=total;feed.source.coverage='已保存可读取的官方历史场次；'+feed.warning+'，不补写缺失赛果';}}
 else if(record.provider==='algs'){let pending=seasonFeeds.get(record.seasonId);if(!pending){pending=publicFetch(API+'/series/seasons/'+record.seasonId,true).then(p=>normalizeApex(p.series,{name:record.seasonName}));seasonFeeds.set(record.seasonId,pending);pending.catch(()=>seasonFeeds.delete(record.seasonId));}const whole=await pending,event=whole.events.find(e=>e.id===record.id);if(!event)throw new Error('官方未提供该赛事');feed={...whole,events:[event],matches:whole.matches.filter(m=>m.eventId===record.id)};standings=await apexStandings(event);}
 else throw new Error('官方历史渠道未识别');
 if(!feed.matches.length)throw new Error('官方目录有赛事名称，暂无可读取比赛');return {feed,standings};
}
